# Generated by Django 4.1.7 on 2023-02-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=40)),
                ('root', models.CharField(max_length=40)),
                ('root_ascii', models.CharField(max_length=40)),
            ],
        ),
    ]
