# Generated by Django 4.1.7 on 2023-02-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='actor_future',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='verb',
            name='actor_past',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='verb',
            name='actor_present',
            field=models.CharField(default='', max_length=40),
        ),
    ]
